//! `meta.yaml` schema. See SPEC.md §3.

use serde::{Deserialize, Serialize};
use tape_judge::JudgeCallRecord;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Meta {
    pub tape_version: String,
    pub id: String,
    pub created_at: String,
    pub ejected_at: String,
    pub task: String,
    pub recorder: Recorder,
    pub outcome: Outcome,

    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub models: Vec<ModelSummary>,

    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tools: Vec<ToolSummary>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_budget: Option<ToolBudget>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub redaction_summary: Option<RedactionSummary>,

    /// Caller-supplied free-form label for filing / categorisation.
    /// `tape record --label X` populates this; readers can group cassettes
    /// by label without parsing `task`. SPEC §3.2. (Issue #72.)
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub label: Option<String>,

    /// One-or-two-sentence post-investigation summary suitable for pasting
    /// into Slack / Linear / Jira / PR descriptions. Plain UTF-8, ≤280
    /// chars, no newline. Set by `tape recap --set <text>`; cleared by
    /// `tape recap --clear`. Distinct from `task` (pre-investigation
    /// framing) and `liner-notes.md` (200–500 word write-up). (Issue #105.)
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub recap: Option<String>,

    /// Append-only audit trail of every `tape recap` invocation against
    /// this cassette. Each `--set` / `--clear` adds one entry. Empty on
    /// untouched cassettes — same skip-when-empty serde shape as
    /// `models` / `tools`. (Issue #105.)
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub recaps: Vec<RecapEntry>,

    /// OPTIONAL multi-valued facet field — orthogonal low-cardinality
    /// labels for filing, search, and CI gates. Distinct from `label`
    /// (single string, free-form) in that tags COMPOSE: a cassette can
    /// be `bug-fix` AND `auth` AND `regression-baseline`. Writers SHOULD
    /// emit lowercase kebab-case strings; consumers MUST NOT assume
    /// canonicalisation. Empty list serialises as field-absent so
    /// untouched cassettes stay byte-identical. (Issue #93 Step 1.)
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tags: Vec<String>,

    /// Append-only audit trail of every `tape relinernote` invocation
    /// against this cassette. Each successful run adds one entry. Empty
    /// on untouched cassettes — same skip-when-empty serde shape as
    /// `recaps`. The entry carries the SHA-256 of the prior and new
    /// `liner-notes.md` so a reader can reconstruct the regeneration
    /// timeline without keeping every intermediate body. (Issue #71.)
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub relinernotes: Vec<RelinernoteEntry>,

    /// Append-only audit trail of every `tape compact` invocation against
    /// this cassette. Each invocation adds one entry — including no-op
    /// runs where nothing changed, so the audit log captures the
    /// "compact was attempted with these parameters" event independently
    /// of whether any payload was actually truncated. Empty on untouched
    /// cassettes — same skip-when-empty serde shape as `recaps` /
    /// `relinernotes` so existing fixtures stay byte-identical.
    /// (Issue #51 Phase 2, carved per #244.)
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub compactions: Vec<CompactionEntry>,

    /// Provenance record for cassettes generated by `tape new`. Present
    /// only on tapes the `new` subcommand wrote; consumers don't fill
    /// this in for live recordings or for tapes coming through the
    /// eject pipeline. SPEC §11 forward-compat: older readers ignore
    /// unknown top-level keys. (Issue #99.)
    ///
    /// Stored as `meta.new` in the YAML; the Rust field is `new_block`
    /// because `new` is a reserved keyword.
    #[serde(rename = "new", skip_serializing_if = "Option::is_none", default)]
    pub new_block: Option<NewBlock>,
}

/// What `tape new` records about how a cassette was generated. Distinct
/// from `recorder` (live capture) and from `recaps` (post-hoc CLI
/// edits). The template id + version pair lets a future ticket compare
/// against a registry of bundled templates ("am I looking at a
/// pristine `minimal` template, or has the user edited it?").
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NewBlock {
    pub template_id: String,
    pub template_version: String,
    pub generated_at: String,
    /// Names of placeholders that were filled in at generation time
    /// (Step 1 of #99 only fills `task`, but the slot is recorded so a
    /// future step can describe richer substitutions without changing
    /// the schema).
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub placeholders_filled: Vec<String>,
}

/// One row in the `meta.recaps` audit array. Records the wall-clock time
/// of the operation, which side it modified (set vs clear vs auto), and
/// the before/after recap text so a reader can reconstruct the recap
/// timeline without re-running the operations. For `Auto` entries the
/// embedded `judge_call` captures the underlying LLM invocation's audit
/// row (model, prompt/output hashes, scan result, retries, truncation).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RecapEntry {
    pub applied_at: String,
    pub kind: RecapKind,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub prior_recap: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub new_recap: Option<String>,
    /// LLM audit record for entries written by `tape recap --auto`. Always
    /// `None` on `Set` / `Clear` rows; populated on `Auto` rows from the
    /// `JudgeCallRecord` returned by the underlying `tape-judge` call.
    /// Skipped from the YAML when absent so existing fixtures stay byte-
    /// identical. (Issue #151.)
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub judge_call: Option<JudgeCallRecord>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum RecapKind {
    /// `tape recap --set <text>`; `prior_recap` is the pre-existing value
    /// (None on first set), `new_recap` is the value being written.
    Set,
    /// `tape recap --clear`; `prior_recap` is what existed,
    /// `new_recap` is None.
    Clear,
    /// `tape recap --auto`; `prior_recap` is the pre-existing value (if
    /// any), `new_recap` is the model-authored recap that just passed
    /// validation and the defense-in-depth scanner. The `judge_call`
    /// field on the entry holds the LLM audit row. (Issue #151.)
    Auto,
}

/// One row in the `meta.relinernotes` audit array. Records when the
/// regeneration ran, which model + bundled-template id was used, and
/// the SHA-256 of the `liner-notes.md` body on both sides of the swap
/// so a chain of two or more runs can be verified by hash equality
/// (`entry[N].prior_liner_notes_sha256 == entry[N-1].new_liner_notes_sha256`).
/// `judge_call` is the audit row returned by `tape_judge::JudgeClient::complete`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RelinernoteEntry {
    pub applied_at: String,
    pub model: String,
    /// Bundled-template id. Always `"default"` in Phase 1 of #71; the
    /// later `--template-id` flag introduces `terse` / `regulatory` /
    /// `pedagogical` / `merged`.
    pub template_id: String,
    /// `sha256(prior liner-notes.md bytes)` (lowercase hex, no
    /// prefix). Used to verify an append-only chain across multiple
    /// `tape relinernote` runs on the same lineage.
    pub prior_liner_notes_sha256: String,
    /// `sha256(new liner-notes.md bytes)` (lowercase hex, no prefix).
    pub new_liner_notes_sha256: String,
    pub judge_call: JudgeCallRecord,
}

/// One row in the `meta.compactions` audit array. Records when a
/// `tape compact` invocation ran, which compaction kind it applied,
/// the `--max-output-chars` ceiling in effect, and the step numbers
/// of tracks whose payload actually changed. Same shape as
/// `RecapEntry` / `RelinernoteEntry` so consumers can reuse the
/// applied-at iteration pattern. (Issue #51 Phase 2, carved per #244.)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CompactionEntry {
    /// RFC 3339 UTC timestamp with millisecond precision (matches
    /// the `applied_at` shape used by `RecapEntry` /
    /// `RelinernoteEntry`).
    pub applied_at: String,
    pub kind: CompactionKind,
    /// The `--max-output-chars` value in effect for this invocation.
    /// Captured even on no-op runs so an auditor can reconstruct
    /// "what threshold was being applied at time T".
    pub max_chars: usize,
    /// Step numbers of tracks whose payload was modified by this
    /// invocation. Empty on a no-op run (the entry is still
    /// recorded — see the `compactions` field doc comment).
    #[serde(default)]
    pub tracks_affected: Vec<u64>,
}

/// Phase-2 compaction kind. Single-variant on purpose: pins the
/// JSON shape (`kind: truncate_output`) so Phase 3+ can add
/// `DropKind`, `RewriteStub`, etc. without breaking older readers.
/// Mirrors the `RecapKind` forward-compat pattern.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CompactionKind {
    /// `tape compact` truncated one or more oversize string payload
    /// values past `--max-output-chars`. Phase 1 of #51's single
    /// behavior; Phase 3+ adds `DropKind` etc.
    TruncateOutput,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Recorder {
    pub agent: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Outcome {
    Success,
    Failure,
    Abandoned,
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ModelSummary {
    pub vendor: String,
    pub model: String,
    pub calls: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolSummary {
    pub kind: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    pub calls: u64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct ToolBudget {
    pub total_calls: u64,
    pub total_tokens_in: u64,
    pub total_tokens_out: u64,
    pub wall_clock_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RedactionSummary {
    pub rules_applied: Vec<String>,
    pub redaction_count: u64,
}

impl Meta {
    /// Parse `meta.yaml` content.
    pub fn parse(yaml: &str) -> crate::Result<Self> {
        Ok(serde_yaml::from_str(yaml)?)
    }

    /// Serialize to YAML.
    pub fn to_yaml(&self) -> crate::Result<String> {
        Ok(serde_yaml::to_string(self)?)
    }
}

/// Maximum length for `meta.recap`. SPEC-adjacent constant kept here next
/// to the field it bounds so callers (the CLI write path and `tape
/// verify`) share one source of truth. (Issue #105.)
pub const RECAP_MAX_LEN: usize = 280;

/// Validate a candidate `meta.recap` value against the on-disk schema
/// invariants: ≤[`RECAP_MAX_LEN`] chars, no newline characters. Returns
/// a human-readable error message on violation. Used by both the
/// `tape recap --set` CLI write path and the `tape verify` read path so
/// any source of a recap (CLI today, deck tool tomorrow, hand-written
/// cassettes from third-party tooling) is held to the same rule.
pub fn validate_recap_text(s: &str) -> Result<(), String> {
    let len = s.chars().count();
    if len > RECAP_MAX_LEN {
        return Err(format!("recap exceeds {RECAP_MAX_LEN} chars: got {len}"));
    }
    if s.contains('\n') || s.contains('\r') {
        return Err("recap must not contain newline characters".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fresh_meta() -> Meta {
        Meta {
            tape_version: "tape/v0".into(),
            id: "01h8xy00-0000-7000-b8aa-000000000105".into(),
            created_at: "2026-05-06T10:00:00Z".into(),
            ejected_at: "2026-05-06T10:00:30Z".into(),
            task: "test".into(),
            recorder: Recorder {
                agent: "test/0.0.1".into(),
                user: None,
            },
            outcome: Outcome::Success,
            models: vec![],
            tools: vec![],
            tool_budget: None,
            redaction_summary: None,
            label: None,
            recap: None,
            recaps: vec![],
            tags: vec![],
            relinernotes: vec![],
            compactions: vec![],
            new_block: None,
        }
    }

    #[test]
    fn recap_field_absent_when_none_and_recaps_empty() {
        let meta = fresh_meta();
        let yaml = meta.to_yaml().unwrap();
        assert!(
            !yaml.contains("recap"),
            "recap fields must be omitted when None/empty (forward-compat): {yaml}"
        );
    }

    #[test]
    fn tags_field_absent_when_empty() {
        let meta = fresh_meta();
        let yaml = meta.to_yaml().unwrap();
        assert!(
            !yaml.contains("tags"),
            "tags must be omitted when empty (forward-compat): {yaml}"
        );
    }

    #[test]
    fn tags_round_trip_preserves_order_and_values() {
        let mut meta = fresh_meta();
        meta.tags = vec![
            "bug-fix".into(),
            "auth".into(),
            "regression-baseline".into(),
        ];
        let yaml = meta.to_yaml().unwrap();
        // Field should serialize lowercase, list-shaped.
        assert!(yaml.contains("tags:"), "yaml=\n{yaml}");
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.tags, meta.tags);
    }

    #[test]
    fn recap_round_trips() {
        let mut meta = fresh_meta();
        meta.recap = Some("Found a race condition in process_refund().".into());
        meta.recaps.push(RecapEntry {
            applied_at: "2026-05-06T10:00:30Z".into(),
            kind: RecapKind::Set,
            prior_recap: None,
            new_recap: meta.recap.clone(),
            judge_call: None,
        });
        let yaml = meta.to_yaml().unwrap();
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.recap, meta.recap);
        assert_eq!(parsed.recaps, meta.recaps);
    }

    #[test]
    fn validate_recap_accepts_boundaries() {
        assert!(validate_recap_text("").is_ok());
        assert!(validate_recap_text(&"x".repeat(279)).is_ok());
        assert!(validate_recap_text(&"x".repeat(280)).is_ok());
    }

    #[test]
    fn validate_recap_rejects_overlong() {
        let too_long = "x".repeat(281);
        let err = validate_recap_text(&too_long).unwrap_err();
        assert!(err.contains("280"), "{err}");
        assert!(err.contains("281"), "{err}");
    }

    #[test]
    fn validate_recap_rejects_newline() {
        assert!(validate_recap_text("foo\nbar").is_err());
        assert!(validate_recap_text("foo\rbar").is_err());
    }

    #[test]
    fn recap_clear_audit_entry_round_trips() {
        let mut meta = fresh_meta();
        meta.recaps.push(RecapEntry {
            applied_at: "2026-05-06T10:00:30Z".into(),
            kind: RecapKind::Clear,
            prior_recap: Some("old text".into()),
            new_recap: None,
            judge_call: None,
        });
        let yaml = meta.to_yaml().unwrap();
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.recaps.len(), 1);
        assert_eq!(parsed.recaps[0].kind, RecapKind::Clear);
        assert_eq!(parsed.recaps[0].prior_recap.as_deref(), Some("old text"));
        assert!(parsed.recaps[0].new_recap.is_none());
    }

    #[test]
    fn recap_auto_entry_round_trips_with_judge_call() {
        use tape_judge::record::ScanOutcome;

        let mut meta = fresh_meta();
        let judge_call = JudgeCallRecord {
            ts: "2026-05-14T09:00:00.123Z".into(),
            model: "claude-haiku-4-5".into(),
            prompt_hash: "abc123".into(),
            output_hash: "def456".into(),
            scan_result: ScanOutcome::Clean,
            retry_count: 0,
            truncated: false,
        };
        meta.recap = Some("Auto-generated summary of the cassette's outcome.".into());
        meta.recaps.push(RecapEntry {
            applied_at: "2026-05-14T09:00:00.123Z".into(),
            kind: RecapKind::Auto,
            prior_recap: None,
            new_recap: meta.recap.clone(),
            judge_call: Some(judge_call.clone()),
        });
        let yaml = meta.to_yaml().unwrap();
        // The `auto` discriminant must serialize lowercase, matching
        // the existing `set` / `clear` conventions.
        assert!(yaml.contains("kind: auto"), "yaml=\n{yaml}");
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.recaps.len(), 1);
        assert_eq!(parsed.recaps[0].kind, RecapKind::Auto);
        assert_eq!(parsed.recaps[0].judge_call.as_ref(), Some(&judge_call));
    }

    #[test]
    fn recap_judge_call_omitted_when_none() {
        // Pre-#151 cassettes have no `judge_call` field on Set/Clear rows.
        // Round-trip a Set entry and assert the field is absent from YAML
        // so the file stays byte-compatible with older readers.
        let mut meta = fresh_meta();
        meta.recap = Some("hand-written".into());
        meta.recaps.push(RecapEntry {
            applied_at: "2026-05-06T10:00:30Z".into(),
            kind: RecapKind::Set,
            prior_recap: None,
            new_recap: Some("hand-written".into()),
            judge_call: None,
        });
        let yaml = meta.to_yaml().unwrap();
        assert!(
            !yaml.contains("judge_call"),
            "judge_call must be omitted when None: {yaml}"
        );
    }

    #[test]
    fn relinernotes_field_absent_when_empty() {
        let meta = fresh_meta();
        let yaml = meta.to_yaml().unwrap();
        assert!(
            !yaml.contains("relinernotes"),
            "relinernotes must be omitted when empty (forward-compat): {yaml}"
        );
    }

    #[test]
    fn relinernotes_entry_round_trips_with_judge_call() {
        use tape_judge::record::ScanOutcome;

        let mut meta = fresh_meta();
        let judge_call = JudgeCallRecord {
            ts: "2026-05-14T09:00:00.123Z".into(),
            model: "claude-haiku-4-5".into(),
            prompt_hash: "abc123".into(),
            output_hash: "def456".into(),
            scan_result: ScanOutcome::Clean,
            retry_count: 0,
            truncated: false,
        };
        meta.relinernotes.push(RelinernoteEntry {
            applied_at: "2026-05-14T09:00:00.123Z".into(),
            model: "claude-haiku-4-5".into(),
            template_id: "default".into(),
            prior_liner_notes_sha256: "0".repeat(64),
            new_liner_notes_sha256: "1".repeat(64),
            judge_call: judge_call.clone(),
        });
        let yaml = meta.to_yaml().unwrap();
        assert!(yaml.contains("relinernotes:"), "yaml=\n{yaml}");
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.relinernotes.len(), 1);
        assert_eq!(parsed.relinernotes[0].model, "claude-haiku-4-5");
        assert_eq!(parsed.relinernotes[0].template_id, "default");
        assert_eq!(parsed.relinernotes[0].judge_call, judge_call);
    }

    // =====================================================================
    // Phase 2 of #51 (carved per #244): `compactions[]` audit ledger.
    // =====================================================================

    #[test]
    fn compactions_field_absent_when_empty() {
        let meta = fresh_meta();
        let yaml = meta.to_yaml().unwrap();
        assert!(
            !yaml.contains("compactions"),
            "untouched cassettes must stay byte-identical: {yaml}"
        );
        // Round trip: parsed compactions stay empty.
        let parsed = Meta::parse(&yaml).unwrap();
        assert!(parsed.compactions.is_empty());
    }

    #[test]
    fn compaction_entry_round_trips_with_lowercase_snake_kind() {
        let mut meta = fresh_meta();
        meta.compactions.push(CompactionEntry {
            applied_at: "2026-05-16T10:00:00.000Z".into(),
            kind: CompactionKind::TruncateOutput,
            max_chars: 1024,
            tracks_affected: vec![3, 5, 9],
        });
        let yaml = meta.to_yaml().unwrap();
        // Pinning: enum is rename_all = "snake_case", so the kind
        // round-trips as `truncate_output` (not `TruncateOutput`).
        assert!(
            yaml.contains("kind: truncate_output"),
            "expected snake_case kind in: {yaml}"
        );
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.compactions.len(), 1);
        assert_eq!(parsed.compactions[0].kind, CompactionKind::TruncateOutput);
        assert_eq!(parsed.compactions[0].max_chars, 1024);
        assert_eq!(parsed.compactions[0].tracks_affected, vec![3, 5, 9]);
        assert_eq!(parsed.compactions[0].applied_at, "2026-05-16T10:00:00.000Z");
    }

    #[test]
    fn compactions_array_appends_in_order_across_two_entries() {
        let mut meta = fresh_meta();
        meta.compactions.push(CompactionEntry {
            applied_at: "2026-05-16T10:00:00.000Z".into(),
            kind: CompactionKind::TruncateOutput,
            max_chars: 1024,
            tracks_affected: vec![2],
        });
        meta.compactions.push(CompactionEntry {
            applied_at: "2026-05-16T10:05:00.000Z".into(),
            kind: CompactionKind::TruncateOutput,
            max_chars: 512,
            tracks_affected: vec![2, 4],
        });
        let yaml = meta.to_yaml().unwrap();
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.compactions.len(), 2);
        assert_eq!(parsed.compactions[0].max_chars, 1024);
        assert_eq!(parsed.compactions[1].max_chars, 512);
        assert_eq!(parsed.compactions[1].tracks_affected, vec![2, 4]);
        assert!(parsed.compactions[0].applied_at < parsed.compactions[1].applied_at);
    }

    #[test]
    fn no_op_compaction_entry_with_empty_tracks_affected_round_trips() {
        let mut meta = fresh_meta();
        meta.compactions.push(CompactionEntry {
            applied_at: "2026-05-16T10:00:00.000Z".into(),
            kind: CompactionKind::TruncateOutput,
            max_chars: 1024,
            tracks_affected: vec![],
        });
        let yaml = meta.to_yaml().unwrap();
        let parsed = Meta::parse(&yaml).unwrap();
        assert_eq!(parsed.compactions.len(), 1);
        assert!(parsed.compactions[0].tracks_affected.is_empty());
    }
}
